<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 9.0.0 (20230911.1827)
 -->
<!-- Title: MLOps Pipeline Pages: 1 -->
<svg width="918pt" height="3940pt"
 viewBox="0.00 0.00 918.00 3939.60" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(144 3795.6)">
<title>MLOps Pipeline</title>
<polygon fill="white" stroke="none" points="-144,144 -144,-3795.6 774,-3795.6 774,144 -144,144"/>
<text text-anchor="middle" x="315" y="-8.5" font-family="Sans-Serif" font-size="15.00" fill="#2d3436">MLOps Pipeline</text>
<g id="clust1" class="cluster">
<title>cluster_Layer 1 — Data</title>
<path fill="#e5f5fd" stroke="#aeb6be" d="M20,-2820.4C20,-2820.4 112,-2820.4 112,-2820.4 118,-2820.4 124,-2826.4 124,-2832.4 124,-2832.4 124,-3631.6 124,-3631.6 124,-3637.6 118,-3643.6 112,-3643.6 112,-3643.6 20,-3643.6 20,-3643.6 14,-3643.6 8,-3637.6 8,-3631.6 8,-3631.6 8,-2832.4 8,-2832.4 8,-2826.4 14,-2820.4 20,-2820.4"/>
<text text-anchor="middle" x="53.32" y="-3628.8" font-family="Sans-Serif" font-size="12.00" fill="#2d3436">Layer 1 — Data</text>
</g>
<g id="clust2" class="cluster">
<title>cluster_Layer 2 — Processing</title>
<path fill="#e5f5fd" stroke="#aeb6be" d="M228,-2510.8C228,-2510.8 323,-2510.8 323,-2510.8 329,-2510.8 335,-2516.8 335,-2522.8 335,-2522.8 335,-3322 335,-3322 335,-3328 329,-3334 323,-3334 323,-3334 228,-3334 228,-3334 222,-3334 216,-3328 216,-3322 216,-3322 216,-2522.8 216,-2522.8 216,-2516.8 222,-2510.8 228,-2510.8"/>
<text text-anchor="middle" x="275.99" y="-3319.2" font-family="Sans-Serif" font-size="12.00" fill="#2d3436">Layer 2 — Processing</text>
</g>
<g id="clust3" class="cluster">
<title>cluster_Layer 3 — Training</title>
<path fill="#e5f5fd" stroke="#aeb6be" d="M100,-1582C100,-1582 401,-1582 401,-1582 407,-1582 413,-1588 413,-1594 413,-1594 413,-2393.2 413,-2393.2 413,-2399.2 407,-2405.2 401,-2405.2 401,-2405.2 100,-2405.2 100,-2405.2 94,-2405.2 88,-2399.2 88,-2393.2 88,-2393.2 88,-1594 88,-1594 88,-1588 94,-1582 100,-1582"/>
<text text-anchor="middle" x="142.65" y="-2390.4" font-family="Sans-Serif" font-size="12.00" fill="#2d3436">Layer 3 — Training</text>
</g>
<g id="clust4" class="cluster">
<title>cluster_Layer 4 — Serving</title>
<path fill="#e5f5fd" stroke="#aeb6be" d="M309,-653.2C309,-653.2 401,-653.2 401,-653.2 407,-653.2 413,-659.2 413,-665.2 413,-665.2 413,-1464.4 413,-1464.4 413,-1470.4 407,-1476.4 401,-1476.4 401,-1476.4 309,-1476.4 309,-1476.4 303,-1476.4 297,-1470.4 297,-1464.4 297,-1464.4 297,-665.2 297,-665.2 297,-659.2 303,-653.2 309,-653.2"/>
<text text-anchor="middle" x="349.65" y="-1461.6" font-family="Sans-Serif" font-size="12.00" fill="#2d3436">Layer 4 — Serving</text>
</g>
<g id="clust5" class="cluster">
<title>cluster_Layer 5 — Deploy</title>
<path fill="#e5f5fd" stroke="#aeb6be" d="M518,-34C518,-34 610,-34 610,-34 616,-34 622,-40 622,-46 622,-46 622,-1154.8 622,-1154.8 622,-1160.8 616,-1166.8 610,-1166.8 610,-1166.8 518,-1166.8 518,-1166.8 512,-1166.8 506,-1160.8 506,-1154.8 506,-1154.8 506,-46 506,-46 506,-40 512,-34 518,-34"/>
<text text-anchor="middle" x="557.65" y="-1152" font-family="Sans-Serif" font-size="12.00" fill="#2d3436">Layer 5 — Deploy</text>
</g>
<!-- 398cf606823943eb8a689b9c8c03ab68 -->
<g id="node1" class="node">
<title>398cf606823943eb8a689b9c8c03ab68</title>
<image xlink:href="https://clouda.ai/var/task/resources/programming/language/python.png" width="100.8px" height="100.8px" preserveAspectRatio="xMinYMin meet" x="15.6" y="-3580.8"/>
<text text-anchor="middle" x="66" y="-3467.1" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">churn.csv</text>
<text text-anchor="middle" x="66" y="-3451.5" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">(Raw Kaggle dataset)</text>
</g>
<!-- 3727beefd8624d17851eb3f6f8be5d42 -->
<g id="node2" class="node">
<title>3727beefd8624d17851eb3f6f8be5d42</title>
<image xlink:href="https://clouda.ai/var/task/resources/onprem/vcs/github.png" width="100.8px" height="100.8px" preserveAspectRatio="xMinYMin meet" x="15.6" y="-3271.2"/>
<text text-anchor="middle" x="66" y="-3157.5" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">DVC</text>
<text text-anchor="middle" x="66" y="-3141.9" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">(Data versioning)</text>
</g>
<!-- 398cf606823943eb8a689b9c8c03ab68&#45;&gt;3727beefd8624d17851eb3f6f8be5d42 -->
<g id="edge1" class="edge">
<title>398cf606823943eb8a689b9c8c03ab68&#45;&gt;3727beefd8624d17851eb3f6f8be5d42</title>
<path fill="none" stroke="darkgray" d="M66,-3447.84C66,-3447.84 66,-3314.91 66,-3314.91"/>
<polygon fill="darkgray" stroke="darkgray" points="69.5,-3314.91 66,-3304.91 62.5,-3314.91 69.5,-3314.91"/>
</g>
<!-- 47d42b811d01439787fb2875beb61c35 -->
<g id="node4" class="node">
<title>47d42b811d01439787fb2875beb61c35</title>
<image xlink:href="https://clouda.ai/var/task/resources/programming/language/python.png" width="100.8px" height="100.8px" preserveAspectRatio="xMinYMin meet" x="224.6" y="-3271.2"/>
<text text-anchor="middle" x="275" y="-3157.5" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">preprocess.py</text>
<text text-anchor="middle" x="275" y="-3141.9" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">(Clean, encode, split)</text>
</g>
<!-- 398cf606823943eb8a689b9c8c03ab68&#45;&gt;47d42b811d01439787fb2875beb61c35 -->
<g id="edge14" class="edge">
<title>398cf606823943eb8a689b9c8c03ab68&#45;&gt;47d42b811d01439787fb2875beb61c35</title>
<path fill="none" stroke="darkgray" d="M116.33,-3530C178.17,-3530 275,-3530 275,-3530 275,-3530 275,-3314.77 275,-3314.77"/>
<polygon fill="darkgray" stroke="darkgray" points="278.5,-3314.77 275,-3304.77 271.5,-3314.77 278.5,-3314.77"/>
</g>
<!-- 0924b350c4744a98b77b2e325a9c033a -->
<g id="node3" class="node">
<title>0924b350c4744a98b77b2e325a9c033a</title>
<image xlink:href="https://clouda.ai/var/task/resources/onprem/compute/server.png" width="100.8px" height="100.8px" preserveAspectRatio="xMinYMin meet" x="15.6" y="-2961.6"/>
<text text-anchor="middle" x="66" y="-2847.9" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">Google Drive</text>
<text text-anchor="middle" x="66" y="-2832.3" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">(Free remote store)</text>
</g>
<!-- 3727beefd8624d17851eb3f6f8be5d42&#45;&gt;0924b350c4744a98b77b2e325a9c033a -->
<g id="edge2" class="edge">
<title>3727beefd8624d17851eb3f6f8be5d42&#45;&gt;0924b350c4744a98b77b2e325a9c033a</title>
<path fill="none" stroke="darkgray" d="M66,-3138.24C66,-3138.24 66,-3005.31 66,-3005.31"/>
<polygon fill="darkgray" stroke="darkgray" points="69.5,-3005.31 66,-2995.31 62.5,-3005.31 69.5,-3005.31"/>
</g>
<!-- edc05ccd301e457995c330f351c47a69 -->
<g id="node5" class="node">
<title>edc05ccd301e457995c330f351c47a69</title>
<image xlink:href="https://clouda.ai/var/task/resources/programming/language/python.png" width="100.8px" height="100.8px" preserveAspectRatio="xMinYMin meet" x="224.6" y="-2961.6"/>
<text text-anchor="middle" x="275" y="-2847.9" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">Pandas / NumPy</text>
<text text-anchor="middle" x="275" y="-2832.3" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">(Data transformation)</text>
</g>
<!-- 47d42b811d01439787fb2875beb61c35&#45;&gt;edc05ccd301e457995c330f351c47a69 -->
<g id="edge3" class="edge">
<title>47d42b811d01439787fb2875beb61c35&#45;&gt;edc05ccd301e457995c330f351c47a69</title>
<path fill="none" stroke="darkgray" d="M275,-3138.24C275,-3138.24 275,-3005.31 275,-3005.31"/>
<polygon fill="darkgray" stroke="darkgray" points="278.5,-3005.31 275,-2995.31 271.5,-3005.31 278.5,-3005.31"/>
</g>
<!-- 3f2767285e964fb3944cabd91601ec0c -->
<g id="node6" class="node">
<title>3f2767285e964fb3944cabd91601ec0c</title>
<image xlink:href="https://clouda.ai/var/task/resources/onprem/database/postgresql.png" width="100.8px" height="100.8px" preserveAspectRatio="xMinYMin meet" x="224.6" y="-2652"/>
<text text-anchor="middle" x="275" y="-2538.3" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">train.csv / test.csv</text>
<text text-anchor="middle" x="275" y="-2522.7" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">(Clean split output)</text>
</g>
<!-- edc05ccd301e457995c330f351c47a69&#45;&gt;3f2767285e964fb3944cabd91601ec0c -->
<g id="edge4" class="edge">
<title>edc05ccd301e457995c330f351c47a69&#45;&gt;3f2767285e964fb3944cabd91601ec0c</title>
<path fill="none" stroke="darkgray" d="M275,-2828.64C275,-2828.64 275,-2695.71 275,-2695.71"/>
<polygon fill="darkgray" stroke="darkgray" points="278.5,-2695.71 275,-2685.71 271.5,-2695.71 278.5,-2695.71"/>
</g>
<!-- 29072908662b4e51a842e5a304bfc1fa -->
<g id="node7" class="node">
<title>29072908662b4e51a842e5a304bfc1fa</title>
<image xlink:href="https://clouda.ai/var/task/resources/programming/language/python.png" width="100.8px" height="100.8px" preserveAspectRatio="xMinYMin meet" x="224.6" y="-2342.4"/>
<text text-anchor="middle" x="275" y="-2228.7" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">train.py</text>
<text text-anchor="middle" x="275" y="-2213.1" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">(RandomForest fit)</text>
</g>
<!-- 3f2767285e964fb3944cabd91601ec0c&#45;&gt;29072908662b4e51a842e5a304bfc1fa -->
<g id="edge15" class="edge">
<title>3f2767285e964fb3944cabd91601ec0c&#45;&gt;29072908662b4e51a842e5a304bfc1fa</title>
<path fill="none" stroke="darkgray" d="M275,-2519.04C275,-2519.04 275,-2386.11 275,-2386.11"/>
<polygon fill="darkgray" stroke="darkgray" points="278.5,-2386.11 275,-2376.11 271.5,-2386.11 278.5,-2386.11"/>
</g>
<!-- 4387169bc45848f886af8c5c829559d5 -->
<g id="node8" class="node">
<title>4387169bc45848f886af8c5c829559d5</title>
<image xlink:href="https://clouda.ai/var/task/resources/programming/language/python.png" width="100.8px" height="100.8px" preserveAspectRatio="xMinYMin meet" x="145.6" y="-2032.8"/>
<text text-anchor="middle" x="196" y="-1919.1" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">scikit&#45;learn</text>
<text text-anchor="middle" x="196" y="-1903.5" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">(ML training)</text>
</g>
<!-- 29072908662b4e51a842e5a304bfc1fa&#45;&gt;4387169bc45848f886af8c5c829559d5 -->
<g id="edge5" class="edge">
<title>29072908662b4e51a842e5a304bfc1fa&#45;&gt;4387169bc45848f886af8c5c829559d5</title>
<path fill="none" stroke="darkgray" d="M235.5,-2209.44C235.5,-2209.44 235.5,-2076.51 235.5,-2076.51"/>
<polygon fill="darkgray" stroke="darkgray" points="239,-2076.51 235.5,-2066.51 232,-2076.51 239,-2076.51"/>
</g>
<!-- faf491fbc7944eac9f7caeff3e93c021 -->
<g id="node10" class="node">
<title>faf491fbc7944eac9f7caeff3e93c021</title>
<image xlink:href="https://clouda.ai/var/task/resources/onprem/compute/server.png" width="100.8px" height="100.8px" preserveAspectRatio="xMinYMin meet" x="304.6" y="-1723.2"/>
<text text-anchor="middle" x="355" y="-1609.5" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">model.pkl +</text>
<text text-anchor="middle" x="355" y="-1593.9" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">feature_names.json</text>
</g>
<!-- 29072908662b4e51a842e5a304bfc1fa&#45;&gt;faf491fbc7944eac9f7caeff3e93c021 -->
<g id="edge7" class="edge">
<title>29072908662b4e51a842e5a304bfc1fa&#45;&gt;faf491fbc7944eac9f7caeff3e93c021</title>
<path fill="none" stroke="darkgray" d="M318.47,-2209.45C318.47,-2209.45 318.47,-1766.78 318.47,-1766.78"/>
<polygon fill="darkgray" stroke="darkgray" points="321.97,-1766.78 318.47,-1756.78 314.97,-1766.78 321.97,-1766.78"/>
</g>
<!-- 5ab7f03b4ba649b1b8feea26bbc477d6 -->
<g id="node9" class="node">
<title>5ab7f03b4ba649b1b8feea26bbc477d6</title>
<image xlink:href="https://clouda.ai/var/task/resources/programming/language/python.png" width="100.8px" height="100.8px" preserveAspectRatio="xMinYMin meet" x="95.6" y="-1723.2"/>
<text text-anchor="middle" x="146" y="-1609.5" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">MLflow</text>
<text text-anchor="middle" x="146" y="-1593.9" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">(Experiment tracking)</text>
</g>
<!-- 4387169bc45848f886af8c5c829559d5&#45;&gt;5ab7f03b4ba649b1b8feea26bbc477d6 -->
<g id="edge6" class="edge">
<title>4387169bc45848f886af8c5c829559d5&#45;&gt;5ab7f03b4ba649b1b8feea26bbc477d6</title>
<path fill="none" stroke="darkgray" d="M171,-1899.84C171,-1899.84 171,-1766.91 171,-1766.91"/>
<polygon fill="darkgray" stroke="darkgray" points="174.5,-1766.91 171,-1756.91 167.5,-1766.91 174.5,-1766.91"/>
</g>
<!-- 4387169bc45848f886af8c5c829559d5&#45;&gt;faf491fbc7944eac9f7caeff3e93c021 -->
<g id="edge8" class="edge">
<title>4387169bc45848f886af8c5c829559d5&#45;&gt;faf491fbc7944eac9f7caeff3e93c021</title>
<path fill="none" stroke="darkgray" d="M246.34,-1982C277.47,-1982 311.53,-1982 311.53,-1982 311.53,-1982 311.53,-1766.77 311.53,-1766.77"/>
<polygon fill="darkgray" stroke="darkgray" points="315.03,-1766.77 311.53,-1756.77 308.03,-1766.77 315.03,-1766.77"/>
</g>
<!-- 238820f16bff4dec8306adee6d2ce13a -->
<g id="node11" class="node">
<title>238820f16bff4dec8306adee6d2ce13a</title>
<image xlink:href="https://clouda.ai/var/task/resources/programming/language/python.png" width="100.8px" height="100.8px" preserveAspectRatio="xMinYMin meet" x="304.6" y="-1413.6"/>
<text text-anchor="middle" x="355" y="-1299.9" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">predict.py</text>
<text text-anchor="middle" x="355" y="-1284.3" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">(Inference helper)</text>
</g>
<!-- faf491fbc7944eac9f7caeff3e93c021&#45;&gt;238820f16bff4dec8306adee6d2ce13a -->
<g id="edge16" class="edge">
<title>faf491fbc7944eac9f7caeff3e93c021&#45;&gt;238820f16bff4dec8306adee6d2ce13a</title>
<path fill="none" stroke="darkgray" stroke-dasharray="5,2" d="M355,-1590.24C355,-1590.24 355,-1457.31 355,-1457.31"/>
<polygon fill="darkgray" stroke="darkgray" points="358.5,-1457.31 355,-1447.31 351.5,-1457.31 358.5,-1457.31"/>
</g>
<!-- 57ccb91ec6824651a1a9b45db1e31f70 -->
<g id="node12" class="node">
<title>57ccb91ec6824651a1a9b45db1e31f70</title>
<image xlink:href="https://clouda.ai/var/task/resources/programming/language/python.png" width="100.8px" height="100.8px" preserveAspectRatio="xMinYMin meet" x="304.6" y="-1104"/>
<text text-anchor="middle" x="355" y="-990.3" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">FastAPI</text>
<text text-anchor="middle" x="355" y="-974.7" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">(REST API server)</text>
</g>
<!-- 238820f16bff4dec8306adee6d2ce13a&#45;&gt;57ccb91ec6824651a1a9b45db1e31f70 -->
<g id="edge9" class="edge">
<title>238820f16bff4dec8306adee6d2ce13a&#45;&gt;57ccb91ec6824651a1a9b45db1e31f70</title>
<path fill="none" stroke="darkgray" d="M355,-1280.64C355,-1280.64 355,-1147.71 355,-1147.71"/>
<polygon fill="darkgray" stroke="darkgray" points="358.5,-1147.71 355,-1137.71 351.5,-1147.71 358.5,-1147.71"/>
</g>
<!-- 5185c0c66949470ea4b5f867dd2f2075 -->
<g id="node14" class="node">
<title>5185c0c66949470ea4b5f867dd2f2075</title>
<image xlink:href="https://clouda.ai/var/task/resources/onprem/container/docker.png" width="100.8px" height="100.8px" preserveAspectRatio="xMinYMin meet" x="513.6" y="-1104"/>
<text text-anchor="middle" x="564" y="-990.3" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">Docker</text>
<text text-anchor="middle" x="564" y="-974.7" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">(Containerise app)</text>
</g>
<!-- 238820f16bff4dec8306adee6d2ce13a&#45;&gt;5185c0c66949470ea4b5f867dd2f2075 -->
<g id="edge17" class="edge">
<title>238820f16bff4dec8306adee6d2ce13a&#45;&gt;5185c0c66949470ea4b5f867dd2f2075</title>
<path fill="none" stroke="darkgray" d="M405.33,-1363C467.17,-1363 564,-1363 564,-1363 564,-1363 564,-1147.62 564,-1147.62"/>
<polygon fill="darkgray" stroke="darkgray" points="567.5,-1147.62 564,-1137.62 560.5,-1147.62 567.5,-1147.62"/>
</g>
<!-- 14f1f0b33028492fbcfb36e68274db39 -->
<g id="node13" class="node">
<title>14f1f0b33028492fbcfb36e68274db39</title>
<image xlink:href="https://clouda.ai/var/task/resources/onprem/compute/server.png" width="100.8px" height="100.8px" preserveAspectRatio="xMinYMin meet" x="304.6" y="-794.4"/>
<text text-anchor="middle" x="355" y="-680.7" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">Uvicorn</text>
<text text-anchor="middle" x="355" y="-665.1" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">(ASGI server)</text>
</g>
<!-- 57ccb91ec6824651a1a9b45db1e31f70&#45;&gt;14f1f0b33028492fbcfb36e68274db39 -->
<g id="edge10" class="edge">
<title>57ccb91ec6824651a1a9b45db1e31f70&#45;&gt;14f1f0b33028492fbcfb36e68274db39</title>
<path fill="none" stroke="darkgray" d="M338.2,-971.04C338.2,-971.04 338.2,-838.11 338.2,-838.11"/>
<polygon fill="darkgray" stroke="darkgray" points="341.7,-838.11 338.2,-828.11 334.7,-838.11 341.7,-838.11"/>
</g>
<!-- 545df617bb6147ff8cb04548ac3b126b -->
<g id="node15" class="node">
<title>545df617bb6147ff8cb04548ac3b126b</title>
<image xlink:href="https://clouda.ai/var/task/resources/programming/language/python.png" width="100.8px" height="100.8px" preserveAspectRatio="xMinYMin meet" x="513.6" y="-794.4"/>
<text text-anchor="middle" x="564" y="-679.5" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">pytest tests</text>
</g>
<!-- 57ccb91ec6824651a1a9b45db1e31f70&#45;&gt;545df617bb6147ff8cb04548ac3b126b -->
<g id="edge18" class="edge">
<title>57ccb91ec6824651a1a9b45db1e31f70&#45;&gt;545df617bb6147ff8cb04548ac3b126b</title>
<path fill="none" stroke="darkgray" d="M371.8,-971.24C371.8,-933.92 371.8,-898 371.8,-898 371.8,-898 547.2,-898 547.2,-898 547.2,-898 547.2,-823.51 547.2,-823.51"/>
<polygon fill="darkgray" stroke="darkgray" points="550.7,-823.51 547.2,-813.51 543.7,-823.51 550.7,-823.51"/>
</g>
<!-- 4b93feb3d6c54a9c954cea908bc56fc1 -->
<g id="node16" class="node">
<title>4b93feb3d6c54a9c954cea908bc56fc1</title>
<image xlink:href="https://clouda.ai/var/task/resources/onprem/ci/github-actions.png" width="100.8px" height="100.8px" preserveAspectRatio="xMinYMin meet" x="513.6" y="-484.8"/>
<text text-anchor="middle" x="564" y="-371.1" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">GitHub Actions</text>
<text text-anchor="middle" x="564" y="-355.5" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">(CI/CD pipelines)</text>
</g>
<!-- 14f1f0b33028492fbcfb36e68274db39&#45;&gt;4b93feb3d6c54a9c954cea908bc56fc1 -->
<g id="edge19" class="edge">
<title>14f1f0b33028492fbcfb36e68274db39&#45;&gt;4b93feb3d6c54a9c954cea908bc56fc1</title>
<path fill="none" stroke="darkgray" d="M405.25,-668C462.19,-668 547.2,-668 547.2,-668 547.2,-668 547.2,-528.6 547.2,-528.6"/>
<polygon fill="darkgray" stroke="darkgray" points="550.7,-528.6 547.2,-518.6 543.7,-528.6 550.7,-528.6"/>
</g>
<!-- 5185c0c66949470ea4b5f867dd2f2075&#45;&gt;545df617bb6147ff8cb04548ac3b126b -->
<g id="edge11" class="edge">
<title>5185c0c66949470ea4b5f867dd2f2075&#45;&gt;545df617bb6147ff8cb04548ac3b126b</title>
<path fill="none" stroke="darkgray" d="M580.8,-971.04C580.8,-971.04 580.8,-823.74 580.8,-823.74"/>
<polygon fill="darkgray" stroke="darkgray" points="584.3,-823.74 580.8,-813.74 577.3,-823.74 584.3,-823.74"/>
</g>
<!-- 545df617bb6147ff8cb04548ac3b126b&#45;&gt;4b93feb3d6c54a9c954cea908bc56fc1 -->
<g id="edge12" class="edge">
<title>545df617bb6147ff8cb04548ac3b126b&#45;&gt;4b93feb3d6c54a9c954cea908bc56fc1</title>
<path fill="none" stroke="darkgray" d="M580.8,-675.67C580.8,-675.67 580.8,-528.66 580.8,-528.66"/>
<polygon fill="darkgray" stroke="darkgray" points="584.3,-528.66 580.8,-518.66 577.3,-528.66 584.3,-528.66"/>
</g>
<!-- ca4668a62575462db0c8f2d0341f5920 -->
<g id="node17" class="node">
<title>ca4668a62575462db0c8f2d0341f5920</title>
<image xlink:href="https://clouda.ai/var/task/resources/onprem/compute/server.png" width="100.8px" height="100.8px" preserveAspectRatio="xMinYMin meet" x="513.6" y="-175.2"/>
<text text-anchor="middle" x="564" y="-61.5" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">Render</text>
<text text-anchor="middle" x="564" y="-45.9" font-family="Sans-Serif" font-size="13.00" fill="#2d3436">(Free hosting)</text>
</g>
<!-- 4b93feb3d6c54a9c954cea908bc56fc1&#45;&gt;ca4668a62575462db0c8f2d0341f5920 -->
<g id="edge13" class="edge">
<title>4b93feb3d6c54a9c954cea908bc56fc1&#45;&gt;ca4668a62575462db0c8f2d0341f5920</title>
<path fill="none" stroke="darkgray" d="M564,-351.84C564,-351.84 564,-218.91 564,-218.91"/>
<polygon fill="darkgray" stroke="darkgray" points="567.5,-218.91 564,-208.91 560.5,-218.91 567.5,-218.91"/>
</g>
</g>
</svg>
